name: Azure PowerShell Automation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PowerShell
        uses: PowerShell/PowerShell@v1

      - name: Install Az Module
        shell: pwsh
        run: |
          Install-Module -Name Az -Force -Scope CurrentUser -AllowClobber
          Import-Module Az

      - name: Run PowerShell Script
        shell: pwsh
        run: ./create-vm.ps1
