name: PowerShell VM Deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run PowerShell script
        shell: pwsh
        run: ./create-vm.ps1
